<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="H.Necessaire.CLI" Version="3.8.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\H.Necessaire.Resiliency\H.Necessaire.Resiliency.csproj" />
	</ItemGroup>

</Project>
